#Connect Type : Service
#Host : localhost
#Database : oracle
#URL : jdbc:oracle:thin:@//localhost:1521/FREE
#Authentication : User / Password
#User : sys
#Password : My1passw

version: '3.8'

services:
  oracle-container:
    image: doctorkirk/oracle-19c:latest-faststart
    container_name: oracledb
    ports:
      - "1521:1521"   # Oracle listener port (default 1521)
      - "5500:5500"   # Oracle EM Express port (default 5500)
    environment:
      - ORACLE_SID=oracle
      - ORACLE_PWD=My1passw
      - ORACLE_MEM=2000
    volumes:
      - ./oradata/:/opt/oracle/oradata
    deploy:
      resources:
        limits:
          memory: 5g
        