version: '3'
services:
  oracledb:
    # do not use
    # container-registry.oracle.com/database/enterprise:latest
    image: container-registry.oracle.com/database/free:latest
    container_name: oracledb
    ports:
      - "1521:1521"
      - "5500:5500"
    environment:
      - ORACLE_PWD=My1passw
    volumes:
      - .:/opt/oracle/oradata
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

#  docker run -it --rm --name oracledb -p 1521:1521 -p 5500:5500 -e ORACLE_PWD=My1passw -v ${PWD}:/opt/oracle/oradata container-registry.oracle.com/database/free:latest
